#!/usr/bin/env bash
# Adds a release's entry (CHANGELOG_ENTRY.md written by prepare.sh) to CHANGELOG.md, right
# below the marker line, so the newest release comes first.
#
#   scripts/release/update-changelog.sh release-out/CHANGELOG_ENTRY.md [CHANGELOG.md]
set -euo pipefail

entry=$1
changelog=${2:-CHANGELOG.md}
marker='<!-- releases: generated by .github/workflows/release.yml, newest first -->'

[[ -s $entry ]] || { echo "::error::no changelog entry in $entry" >&2; exit 1; }
grep -qxF "$marker" "$changelog" || { echo "::error::marker line not found in $changelog" >&2; exit 1; }
heading=$(head -1 "$entry")
if grep -qxF "$heading" "$changelog"; then
    echo "$changelog already has '$heading'"
    exit 0
fi

awk -v marker="$marker" -v entry="$entry" '
    { print }
    $0 == marker {
        print ""
        while ((getline line < entry) > 0) print line
    }
' "$changelog" > "$changelog.new"
mv "$changelog.new" "$changelog"
