apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion '29.0.3'
    defaultConfig {
        applicationId "net.eneiluj.nextcloud.phonetrack"
        minSdkVersion 18
        targetSdkVersion 29
        versionCode 20
        versionName "0.1.0"
        multiDexEnabled true
        vectorDrawables {
            useSupportLibrary true
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        disable 'MissingTranslation'
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    productFlavors {
        normal {
            // yes this is repeated
            applicationId "net.eneiluj.nextcloud.phonetrack"
            resValue "string", "app_name", "PhoneTrack"
            resValue "string", "applicationId", applicationId
        }
        dev {
            applicationId 'net.eneiluj.nextcloud.phonetrack.dev'
            resValue "string", "app_name", "PhoneTrack Dev"
            resValue "string", "applicationId", applicationId
        }
        play {
            applicationId "net.eneiluj.nextcloud.phonetrack.play"
            resValue "string", "app_name", "PhoneTrack"
            resValue "string", "applicationId", applicationId
        }
    }
    flavorDimensions "default"
    // solves cert4android crash
    dataBinding {
        enabled = true
    }
}

dependencies {
    implementation project(':cert4android')
    implementation 'com.github.clans:fab:1.6.4'
    def supportLibVersion = '1.1.0'
    implementation "androidx.appcompat:appcompat:${supportLibVersion}"
    implementation "com.google.android.material:material:${supportLibVersion}"
    implementation "androidx.recyclerview:recyclerview:${supportLibVersion}"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    // needed for cert4android (conflict resolution)
    implementation "androidx.cardview:cardview:1.0.0"
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation 'junit:junit:4.13'
    implementation 'org.osmdroid:osmdroid-android:6.1.6'
    implementation 'org.osmdroid:osmdroid-mapsforge:6.1.6'
    implementation 'com.github.kizitonwose.colorpreference:support:1.0.6'
    implementation 'com.larswerkman:lobsterpicker:1.0.1'
    implementation 'com.github.nextcloud:Android-SingleSignOn:0.5.1'
    //implementation 'com.github.nextcloud:Android-SingleSignOn:-SNAPSHOT'
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.codebutchery.android:gpx_lib:1.0.3'
}
